from typing import Protocol


class AIProviderUnavailable(Exception):
    """AI provider cannot service the request (missing key, SDK failure, bad response)."""


class EvidenceAI(Protocol):
    def discover_startups(self, problem_statement: str, domain: str,
                          location_hint: str = "Maharashtra India") -> list[dict]: ...
    def embed(self, texts: list[str]) -> list[list[float]]: ...
    def extract(self, evidence_text: str, evidence_type: str) -> dict: ...
    def compare_contexts(self, new_ctx: dict, historical_ctx: dict) -> dict: ...
    def draft_explanation(self, decision_output: dict) -> str: ...
