"""proposals and eligibility checks

Revision ID: 55c1785792ed
Revises: fb82bb01dc0a
Create Date: 2026-09-11 00:01:08.617139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c1785792ed'
down_revision: Union[str, None] = 'fb82bb01dc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'ELIGIBLE', 'UNDER_EVALUATION', 'SELECTED', 'REJECTED', name='proposalstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('technical_summary', sa.Text(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='fk_proposals_challenge'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name='fk_proposals_startup'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'startup_id', name='uq_proposal_challenge_startup')
    )
    op.create_index(op.f('ix_proposals_challenge_id'), 'proposals', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_proposals_startup_id'), 'proposals', ['startup_id'], unique=False)
    op.create_table('eligibility_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'PENDING_MANUAL', 'WAIVED', name='checkresult', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('checked_value', sa.Float(), nullable=True),
    sa.Column('waived_by', sa.Integer(), nullable=True),
    sa.Column('waiver_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['eligibility_criteria.id'], name='fk_checks_criterion'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name='fk_checks_proposal'),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], name='fk_checks_waived_by'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_checks_proposal_id'), 'eligibility_checks', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eligibility_checks_proposal_id'), table_name='eligibility_checks')
    op.drop_table('eligibility_checks')
    op.drop_index(op.f('ix_proposals_startup_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_challenge_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
