"""audit logs table

Revision ID: 606cbe18af12
Revises: 
Create Date: 2026-09-10 18:02:02.656611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606cbe18af12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'WAIVE', 'AUTHORIZE', 'REJECT', 'VALIDATE', 'SELECT', 'COMPUTE', 'PUBLISH', 'CLOSE', 'INVOICE', 'APPROVE', 'DISBURSE', 'FINALIZE', 'RESOLVE', name='auditaction', native_enum=False, length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "CREATE RULE audit_logs_no_update AS ON UPDATE TO audit_logs "
        "DO INSTEAD NOTHING;"
    )
    op.execute(
        "CREATE RULE audit_logs_no_delete AS ON DELETE TO audit_logs "
        "DO INSTEAD NOTHING;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP RULE IF EXISTS audit_logs_no_update ON audit_logs;")
    op.execute("DROP RULE IF EXISTS audit_logs_no_delete ON audit_logs;")
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
