"""departments startups users department fk

Revision ID: ae3dc4d91539
Revises: d0720d7c4c47
Create Date: 2026-09-10 23:15:18.032335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3dc4d91539'
down_revision: Union[str, None] = 'd0720d7c4c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('connectivity_tier', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='connectivitytier', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('power_reliability', sa.Enum('STABLE', 'INTERMITTENT', 'UNRELIABLE', name='powerreliability', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('it_maturity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='itmaturity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('settlement_type', sa.Enum('URBAN', 'SEMI_URBAN', 'RURAL', 'TRIBAL', name='settlementtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('terrain_type', sa.Enum('PLAIN', 'HILLY', 'COASTAL', 'DESERT', 'MIXED', name='terraintype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dpiit_number', sa.String(length=100), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('annual_turnover', sa.Float(), nullable=False),
    sa.Column('runway_months', sa.Integer(), nullable=True),
    sa.Column('prior_deployments', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_startups_owner_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id')
    )
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key('fk_users_department', 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_department', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_table('startups')
    op.drop_table('departments')
    # ### end Alembic commands ###
