"""discovered startups and invitations

Revision ID: f14ca30171b7
Revises: 55c1785792ed
Create Date: 2026-09-11 02:03:34.334022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14ca30171b7'
down_revision: Union[str, None] = '55c1785792ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('gemini_search', 'seed_index', name='discoverysource', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='fk_discovered_challenge'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'name', name='uq_discovered_challenge_name')
    )
    op.create_index(op.f('ix_discovered_startups_challenge_id'), 'discovered_startups', ['challenge_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('discovered_startup_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'REGISTERED', 'EXPIRED', name='invitationstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('registered_startup_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='fk_invitations_challenge'),
    sa.ForeignKeyConstraint(['discovered_startup_id'], ['discovered_startups.id'], name='fk_invitations_discovered'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name='fk_invitations_invited_by'),
    sa.ForeignKeyConstraint(['registered_startup_id'], ['startups.id'], name='fk_invitations_registered_startup'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_challenge_id'), 'invitations', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_invitations_invite_code'), 'invitations', ['invite_code'], unique=True)
    # NOTE: spurious fk_audit_logs_user_id drift (autogenerate artifact, ruled out 3x) removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_invite_code'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_challenge_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_discovered_startups_challenge_id'), table_name='discovered_startups')
    op.drop_table('discovered_startups')
    # ### end Alembic commands ###
