"""challenges and eligibility criteria

Revision ID: fb82bb01dc0a
Revises: ae3dc4d91539
Create Date: 2026-09-10 23:36:43.665578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb82bb01dc0a'
down_revision: Union[str, None] = 'ae3dc4d91539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('baseline', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('domain', sa.Enum('water', 'agri', 'health', 'education', 'infrastructure', 'governance', 'transport', 'energy', 'other', name='domaintag', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='challengestatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evaluation_weights', sa.JSON(), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_challenges_department'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_department_id'), 'challenges', ['department_id'], unique=False)
    op.create_table('eligibility_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('criterion_type', sa.Enum('TURNOVER', 'EXPERIENCE', 'DPIIT', 'CUSTOM', name='criteriontype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('operator', sa.Enum('GTE', 'LTE', 'EQ', name='criterionoperator', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_auto_checkable', sa.Boolean(), nullable=False),
    sa.Column('waiver_allowed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='fk_criteria_challenge'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_criteria_challenge_id'), 'eligibility_criteria', ['challenge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eligibility_criteria_challenge_id'), table_name='eligibility_criteria')
    op.drop_table('eligibility_criteria')
    op.drop_index(op.f('ix_challenges_department_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
